import type { Product } from "@/lib/types";

export const products: Product[] = [
  {
    id: "premium-briquettes-10kg",
    name: "Premium Biomass Briquettes (10kg Bag)",
    category: "fuel",
    brand: "Brick Health",
    image: "https://images.unsplash.com/photo-1481660148723-b77ee9184660?w=800&q=80&auto=format&fit=crop",
    price: 5000,
    original_price: 6500,
    description: "Eco-friendly, high-efficiency briquettes manufactured from 100% recycled agricultural waste. Our smokeless briquettes burn hotter and 2x longer than regular wood charcoal, making them the perfect clean energy source for domestic and commercial cooking while preventing deforestation.",
    specifications: {
      "Weight": "10 kg",
      "Material": "Recycled Agricultural Waste (Rice Husks, Coconut Shells)",
      "Burn Time": "Up to 4 hours",
      "Ash Content": "Less than 5%",
      "Smoke Emissions": "Zero (Smokeless & Odorless)"
    },
    tags: ["fuel", "briquettes", "charcoal", "clean-cooking", "eco-friendly"],
    in_stock: true,
    stock_count: 150,
    rating: 4.9,
    review_count: 245,
    variants: [],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "eco-pellets-15kg",
    name: "High-Efficiency Wood Pellets (15kg Bag)",
    category: "fuel",
    brand: "Brick Health",
    image: "https://images.unsplash.com/photo-1758519395874-32df1faf31ed?w=800&q=80&auto=format&fit=crop",
    price: 7500,
    original_price: 9000,
    description: "Highly compressed premium wood pellets designed specifically for forced-draft biomass stoves. Delivers extremely high heat output with near-zero particulate emissions, ensuring a clean, safe, and fast cooking experience.",
    specifications: {
      "Weight": "15 kg",
      "Moisture Content": "Less than 8%",
      "Heat Output Value": "4.8 kWh/kg",
      "Material": "100% Compressed Virgin Wood Residues"
    },
    tags: ["fuel", "pellets", "biomass", "stove-fuel", "high-heat"],
    in_stock: true,
    stock_count: 80,
    rating: 4.7,
    review_count: 98,
    variants: [],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "smokeless-stove-ordinary",
    name: "Premium Smokeless Rocket Cookstove",
    category: "stoves",
    brand: "Brick Health",
    image: "https://images.unsplash.com/photo-1768912742570-e10b7d2b755b?w=800&q=80&auto=format&fit=crop",
    price: 35000,
    original_price: 42000,
    description: "Advanced rocket stove designed for rural and urban households. Features a stainless steel internal combustion chamber and premium refractory insulation. Reduces charcoal or wood consumption by up to 60% and indoor smoke emissions by 80%.",
    specifications: {
      "Chamber Material": "High-Grade Stainless Steel",
      "Body Material": "Powder-Coated Recycled Steel",
      "Weight": "4.2 kg",
      "Dimensions": "32 x 24 x 24 cm",
      "Warranty": "2 years"
    },
    tags: ["stoves", "rocket-stove", "smokeless", "household", "wood-burning"],
    in_stock: true,
    stock_count: 45,
    rating: 4.8,
    review_count: 134,
    variants: [],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "teg-smart-stove",
    name: "Eco-Friendly TEG Smart Cookstove (With USB Charger)",
    category: "stoves",
    brand: "Brick Health",
    image: "https://images.unsplash.com/photo-1773762159808-510a225fcaa1?w=800&q=80&auto=format&fit=crop",
    price: 75000,
    original_price: 90000,
    description: "Our flagship clean energy stove equipped with a Thermoelectric Generator (TEG). It converts excess heat from cooking into 30W of electricity, powering a built-in combustion-enhancing fan for 100% smokeless burning while providing USB power to charge mobile phones and run LED lights in off-grid homes.",
    specifications: {
      "Electricity Output": "5V USB (up to 30W)",
      "Features": "Built-in forced-draft fan, USB port, LED light connector",
      "Battery Buffer": "2,200 mAh integrated Li-ion",
      "Dimensions": "35 x 26 x 26 cm",
      "Warranty": "3 years"
    },
    tags: ["stoves", "teg", "electricity", "smart-cooking", "charging", "off-grid"],
    in_stock: true,
    stock_count: 25,
    rating: 4.9,
    review_count: 67,
    variants: [],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "travel-stove-compact",
    name: "Compact Portable Travel Cookstove",
    category: "stoves",
    brand: "Brick Health",
    image: "https://images.unsplash.com/photo-1768146336038-7be8338850e6?w=800&q=80&auto=format&fit=crop",
    price: 18000,
    original_price: 22000,
    description: "A lightweight, foldable version of our premium rocket stove. Perfect for camping, outdoor excursions, or quick outdoor cooking. Easy to assemble and runs efficiently on wood, briquettes, or twigs.",
    specifications: {
      "Weight": "1.8 kg",
      "Foldable": "Yes",
      "Carrying Bag": "Included",
      "Assembly Time": "Under 1 minute"
    },
    tags: ["stoves", "portable", "camping", "travel", "lightweight", "folding"],
    in_stock: true,
    stock_count: 60,
    rating: 4.6,
    review_count: 42,
    variants: [],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "commercial-teg-stove",
    name: "Industrial Commercial TEG Cookstove",
    category: "stoves",
    brand: "Brick Health",
    image: "https://images.unsplash.com/photo-1709201776398-99a81cfa8634?w=800&q=80&auto=format&fit=crop",
    price: 210000,
    original_price: 250000,
    description: "Heavy-duty commercial clean stove designed for restaurants, schools, and boarding houses. Built with reinforced cast iron and structural steel, it supports pots up to 50L. The integrated TEG powers high-capacity dual forced-draft fans for absolute smoke elimination and high-speed cooking.",
    specifications: {
      "Pot Capacity": "Up to 50 Litres",
      "Body Material": "Reinforced Cast Iron & Heavy Steel",
      "Power System": "Forced Forced-Draft Dual Fans via TEG",
      "Weight": "18.5 kg",
      "Warranty": "5 years"
    },
    tags: ["stoves", "commercial", "restaurant", "heavy-duty", "industrial", "clean-air"],
    in_stock: true,
    stock_count: 12,
    rating: 5.0,
    review_count: 18,
    variants: [],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];
